name: Ruby

on:
  push:
    branches: [ $default-branch ]
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml
  pull_requests:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: run tests
        run: bundle exec rake
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: run rubocop
        run: |
          gem install rubocop
          rubocop

